name: Build and deploy Python app to Azure Web App - flasktranslatorapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'flasktranslatorapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F3049D58FFEC4DC895CDD83B10FB2929 }}

      # - name: Unzip output.tar.gz to /home/site/wwwroot
      #   run: |
      #     echo "Unzipping output.tar.gz to /home/site/wwwroot"
      #     tar -xzf /home/site/wwwroot/output.tar.gz -C /home/site/wwwroot/

      # - name: Set PATH for FFmpeg
      #   run: |
      #     echo "Adding /home/site/wwwroot to PATH"
      #     echo "export PATH=\$PATH:/home/site/wwwroot" >> ~/.bashrc
      #     source ~/.bashrc
    
      - name: Verify FFmpeg installation
        run: |
          ffmpeg --version

      # - name: Install FFmpeg
      #   run: |
      #     ssh -o StrictHostKeyChecking=no kudu_ssh_user@flasktranslatorapp << 'EOF'
      #       cd /home/site/wwwroot
      #       chmod +x install_ffmpeg.sh
      #       ./install_ffmpeg.sh  # Run the script to install FFmpeg
      #     EOF
      # - name: Upload FFmpeg installation script
      #   run: |
      #       echo 'uploading install_ffmpeg.sh script to the App Service...'
      #       scp -o StrictHostKeyChecking=no install_ffmpeg.sh kudu_ssh_user@flasktranslatorapp-bvepdbcvgmh7ffek.scm.azurewebsites.net:/home/site/wwwroot/
          
      # - name: Run FFmpeg installation script
      #   run: |
      #       ssh -T -o StrictHostKeyChecking=no kudu_ssh_user@flasktranslatorapp-bvepdbcvgmh7ffek.scm.azurewebsites.net << 'EOF'
      #         chmod +x /home/site/wwwroot/install_ffmpeg.sh
      #         /home/site/wwwroot/install_ffmpeg.sh
      #       EOF
        
