name: Build and deploy Python app to Azure Web App - flasktranslatorapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Download and Install FFmpeg in Persisted Location
        run: |
            mkdir -p $GITHUB_WORKSPACE/ffmpeg
            cd $GITHUB_WORKSPACE/ffmpeg
            curl -L -o ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
            tar -xf ffmpeg.tar.xz --strip-components=1
            rm ffmpeg.tar.xz
            chmod +x ffmpeg
  
      - name: Move FFmpeg to Persisted Directory
        run: |
            mkdir -p $GITHUB_WORKSPACE/site/wwwroot/bin
            mv $GITHUB_WORKSPACE/ffmpeg/ffmpeg $GITHUB_WORKSPACE/site/wwwroot/bin/
            mv $GITHUB_WORKSPACE/ffmpeg/ffprobe $GITHUB_WORKSPACE/site/wwwroot/bin/
  
      - name: Set Execute Permissions
        run: chmod +x $GITHUB_WORKSPACE/site/wwwroot/bin/ffmpeg $GITHUB_WORKSPACE/site/wwwroot/bin/ffprobe
    
      - name: Verify FFmpeg after Deployment
        run: |
          /home/site/wwwroot/bin/ffmpeg -version

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'flasktranslatorapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F3049D58FFEC4DC895CDD83B10FB2929 }}