name: Build and deploy Python app to Azure Web App - flasktranslatorapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'flasktranslatorapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F3049D58FFEC4DC895CDD83B10FB2929 }}

      - name: Install FFmpeg in Azure Web App
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@flasktranslatorapp.scm.azurewebsites.net << 'EOF'
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          ls -l /usr/bin/ffmpeg  # Verify installation
          EOF
          # sudo apt-get update;
          # sudo apt-get install -y ffmpeg;
          # ls -l /usr/bin/ffmpeg;  # List the ffmpeg binary to verify installation

      - name: Verify FFmpeg Installation
        run: 
          ssh azureuser@flasktranslatorapp.scm.azurewebsites.net "ffmpeg -version"|
          # ffmpeg -version